### ISSUE TITLE
Publish releases to GitHub

### ISSUE THREAD

**Issue by jonafato** [jpec/gnome-shell-extensions#5]
I'd like to package these extensions for [NixOS](https://nixos.org/). These packages are typically built from their GitHub source releases. Can you tag releases here on GitHub for the versions that get uploaded to EGO?

**Comment by jpec** [comment]
I can tag updates if you want, but these extensions are useless since gnome 3.26.
I've added the 3.24 tag.

**Comment by jonafato** [comment]
Thanks! I'm using 3.26, and at least Straight Top Bar seems to work just fine. Why are these extensions incompatible with 3.26?

**Comment by jpec** [comment]
Because since 3.26 top bar background is transparent by default and turns dark when a windows is close. But the top bar is still rounded.

**Comment by jpec** [comment]
I've updated straighttopbar for gnome 3.26 and taged it.
